/** Supported display identifiers shared by commands, configuration, and UI. */
export const themeNames = [
  "ember-tide",
  "charcoal",
  "charcoal-transparent",
  "charcoal-ink",
  "charcoal-ink-transparent",
  "charcoal-copper",
  "charcoal-copper-transparent",
  "charcoal-signal",
  "charcoal-signal-transparent",
  "lichen",
  "lichen-transparent",
  "dusk",
  "dusk-transparent",
  "clay",
  "clay-transparent",
  "nord",
  "kanagawa",
  "gruvbox-material",
  "tokyo-night",
  "catppuccin-mocha",
  "rose-pine-dawn",
  "everforest",
  "solarized-light",
  "solarized-dark",
  "one-dark",
  "dracula",
] as const
export type ThemeName = (typeof themeNames)[number]
