import { readFile, writeFile, mkdir } from "node:fs/promises"
import { dirname, resolve } from "node:path"

// Deliberately small source format: a title, level-two headings, and prose paragraphs.
const root = resolve(import.meta.dir, "..")
const source = await readFile(resolve(root, "docs/manual.md"), "utf8")
const sections = [
  ...source.matchAll(/^## (.+)\n([\s\S]*?)(?=^## |$(?![\s\S]))/gm),
].map((match) => ({ title: match[1]!, body: match[2]!.trim() }))
if (!sections.length || sections[0]!.title !== "NAME")
  throw new Error("Manual must begin with NAME")
const escape = (text: string) =>
  text.replace(/\\/g, "\\e").replace(/-/g, "\\-").replace(/^[.']/gm, "\\&$&")
const date = /<!-- man-date: ([^<>"\n]+) -->/.exec(source)?.[1]
if (!date) throw new Error("Manual requires a man-date comment")
const wrap = (text: string) =>
  text
    .split(/\s+/)
    .reduce<string[]>((lines, word) => {
      const last = lines.at(-1)
      if (last && last.length + word.length < 70)
        lines[lines.length - 1] = `${last} ${word}`
      else lines.push(word)
      return lines
    }, [])
    .join("\n")
const man =
  `.\\" Generated by bun run docs:generate; edit docs/manual.md.\n.TH VIMEX 1 "${date}" "Vimex" "User Commands"\n` +
  sections
    .map(
      (section) =>
        `.SH ${section.title}\n` +
        section.body
          .split(/\n\n+/)
          .map(
            (paragraph, index) =>
              `${index ? ".PP\n" : ""}${escape(wrap(paragraph))}\n`,
          )
          .join(""),
    )
    .join("")
const data = `// Generated by bun run docs:generate; edit docs/manual.md.\nexport const manualSections = ${JSON.stringify(sections, null, 2)} as const\n`
for (const [name, contents] of [
  ["docs/man/vimex.1", man],
  ["packages/ui-opentui-react/src/help/manual.generated.ts", data],
] as const) {
  const path = resolve(root, name)
  if (process.argv.includes("--check")) {
    if ((await readFile(path, "utf8").catch(() => "")) !== contents)
      throw new Error(`${name} is stale; run bun run docs:generate`)
  } else {
    await mkdir(dirname(path), { recursive: true })
    await writeFile(path, contents)
  }
}
